version: '3.8'

services:
  mysql:
    container_name: mysql-simplebanking
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - '3307:3306'
    volumes:
      - ./src/main/resources/db/setup/:/docker-entrypoint-initdb.d/