spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3307/simplebanking}
    username: ${DATASOURCE_USERNAME:simplebanking}
    password: ${DATASOURCE_PASSWORD:simplebankingpass}
    driverClassName: com.mysql.cj.jdbc.Driver